# Generated by Django 5.2.6 on 2025-09-28 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('specification', models.CharField(max_length=100)),
                ('power_info', models.CharField(max_length=50)),
                ('date_installed', models.DateField()),
                ('maintenance_cycle', models.CharField(max_length=20)),
                ('warranty_period', models.CharField(max_length=50)),
                ('contractor_name', models.CharField(max_length=100)),
                ('contractor_phone', models.CharField(max_length=20)),
                ('installer_name', models.CharField(max_length=50)),
                ('installer_phone', models.CharField(max_length=20)),
                ('emergency_name', models.CharField(max_length=50)),
                ('emergency_phone', models.CharField(max_length=20)),
                ('maintenance_name', models.CharField(max_length=50)),
                ('maintenance_phone', models.CharField(max_length=20)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.equipmenttype')),
            ],
        ),
    ]
