# Generated by Django 5.2.6 on 2025-09-28 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '設備大類',
                'verbose_name_plural': '設備大類',
            },
        ),
        migrations.AlterModelOptions(
            name='devices',
            options={'verbose_name': '設備', 'verbose_name_plural': '設備'},
        ),
        migrations.AlterModelOptions(
            name='equipmenttype',
            options={'verbose_name': '設備種類', 'verbose_name_plural': '設備種類'},
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_types', to='devices.equipmentcategory'),
        ),
    ]
