# Generated by Django 5.2.6 on 2025-09-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_equipmentcategory_alter_devices_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='contractor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='contractor_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='date_installed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='emergency_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='installer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='installer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='maintenance_cycle',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='power_info',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='specification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='warranty_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
